### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on Linux x86_64

### ISSUE THREAD

**Issue by rafaeltuelho** [openshift/source-to-image#640]
using release `v1.1.3`...

`s2i build https://github.com/pmorie/simple-ruby.git openshift/ruby-20-centos7 test-ruby-app`

I get...

```
error: Unable to load docker config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ef3a0]

goroutine 1 [running]:
panic(0x7c26e0, 0xc420012160)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/source-to-image/pkg/docker.GetImageRegistryAuth(0x0, 0x7fff89f4c978, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/util.go:67 +0x250
main.newCmdBuild.func1(0xc420097200, 0xc4202a41e0, 0x3, 0x3)
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:118 +0x1003
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).execute(0xc420097200, 0xc4202a4150, 0x3, 0x3, 0xc420097200, 0xc4202a4150)
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420096d80, 0xc420183eb0, 0xc4202593d0, 0xc420097b00)
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420096d80, 0xc420183ea8, 0x1)
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/rsoares/Downloads/gocode/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/main.go:415 +0x660
```

My env is:

```
uname -a                                                                                                                                                               2 ↵
Linux rsoares 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
Release:	7.3
Codename:	Maipo
```

```
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

I tested with the linux binary s2i and tried to compile manually. Both fails.

**Comment by bparees** [comment]
can you share your docker config file, obscuring any credentials/tokens?

**Comment by rafaeltuelho** [comment]
My docker config has only this:

```
cat ~/.docker/config.json 
{
	"auths": {}
}%
```

The docker unit on Systemd:

```
cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
#ExecStart=/usr/bin/dockerd
ExecStart=/usr/bin/dockerd --insecure-registry 172.30.0.0/16 --bip=172.17.42.1/16 -g /docker-storage
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by bparees** [comment]
looks like something doesn't like that you have no auths at all in your docker config.json, as a workaround you can do a docker login to dockerhub (assuming you have a dockerhub account).

(I was able to recreate this locally).

**Comment by rafaeltuelho** [comment]
yeah! after login hub.docker.com it worked fine!
