### ISSUE TITLE
s2i segfaults (source-to-image-1.0.9)

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/source-to-image#822]
```
$ s2i build /tmp/pytest-of-tt/pytest-3/test_s2i_extending0 punchbag:latest
E1107 13:56:28.710361 28202 util.go:60] Unable to load docker config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x557a4ecf8f4e]

goroutine 1 [running]:
panic(0x557a4f056980, 0x557a4f27eb40)
        /usr/lib/golang/src/runtime/panic.go:540 +0x462 fp=0xc4200c3608 sp=0xc4200c3560 pc=0x557a4e9c32a2
runtime.panicmem()
        /usr/lib/golang/src/runtime/panic.go:63 +0x60 fp=0xc4200c3628 sp=0xc4200c3608 pc=0x557a4e9c1fa0
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:367 +0x180 fp=0xc4200c3678 sp=0xc4200c3628 pc=0x557a4e9d99e0
github.com/openshift/source-to-image/pkg/docker.GetImageRegistryAuth(0x0, 0x7ffce06476d8, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/src/github.com/openshift/source-to-image/pkg/docker/util.go:44 +0x1ce fp=0xc4200c3950 sp=0xc4200c3678 pc=0x557a4ecf8f4e
main.newCmdBuild.func1(0xc4201523c0, 0xc420120ba0, 0x2, 0x2)
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/src/github.com/openshift/source-to-image/cmd/s2i/main.go:109 +0xbdb fp=0xc4200c3ce8 sp=0xc4200c3950 pc=0x557a4ed22deb
github.com/spf13/cobra.(*Command).execute(0xc4201523c0, 0xc420120a40, 0x2, 0x2, 0xc4201523c0, 0xc420120a40)
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x20f fp=0xc4200c3d98 sp=0xc4200c3ce8 pc=0x557a4eb546bf
github.com/spf13/cobra.(*Command).Execute(0xc420152000, 0xc4200c3f30, 0x1)
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x2ff fp=0xc4200c3ec8 sp=0xc4200c3d98 pc=0x557a4eb54f6f
main.main()
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/src/github.com/openshift/source-to-image/cmd/s2i/main.go:392 +0x4e6 fp=0xc4200c3f80 sp=0xc4200c3ec8 pc=0x557a4ed21f46
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:185 +0x215 fp=0xc4200c3fe0 sp=0xc4200c3f80 pc=0x557a4e9c4f05
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200c3fe8 sp=0xc4200c3fe0 pc=0x557a4e9f20f1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x557a4f0cba18, 0x557a4f2bbb60, 0x557a4ed2bf78, 0xf, 0x14, 0x1)
        /usr/lib/golang/src/runtime/proc.go:277 +0x132 fp=0xc420034768 sp=0xc420034738 pc=0x557a4e9c53a2
runtime.goparkunlock(0x557a4f2bbb60, 0x557a4ed2bf78, 0xf, 0xc420000114, 0x1)
        /usr/lib/golang/src/runtime/proc.go:283 +0x60 fp=0xc4200347a8 sp=0xc420034768 pc=0x557a4e9c5490
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:235 +0xd0 fp=0xc4200347e0 sp=0xc4200347a8 pc=0x557a4e9c51c0
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200347e8 sp=0xc4200347e0 pc=0x557a4e9f20f1
created by runtime.init.5
        /usr/lib/golang/src/runtime/proc.go:224 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x557a4f0cba18, 0x557a4f2bbca0, 0x557a4ed2adc0, 0xd, 0x557a4e9b7f14, 0x1)
        /usr/lib/golang/src/runtime/proc.go:277 +0x132 fp=0xc420034f60 sp=0xc420034f30 pc=0x557a4e9c53a2
runtime.goparkunlock(0x557a4f2bbca0, 0x557a4ed2adc0, 0xd, 0x14, 0x1)
        /usr/lib/golang/src/runtime/proc.go:283 +0x60 fp=0xc420034fa0 sp=0xc420034f60 pc=0x557a4e9c5490
runtime.bgsweep(0xc420064000)
        /usr/lib/golang/src/runtime/mgcsweep.go:52 +0xa7 fp=0xc420034fd8 sp=0xc420034fa0 pc=0x557a4e9b7fe7
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420034fe0 sp=0xc420034fd8 pc=0x557a4e9f20f1
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:216 +0x5a

goroutine 4 [finalizer wait]:
runtime.gopark(0x557a4f0cba18, 0x557a4f2dbd40, 0x557a4ed2b78a, 0xe, 0x14, 0x1)
        /usr/lib/golang/src/runtime/proc.go:277 +0x132 fp=0xc420035700 sp=0xc4200356d0 pc=0x557a4e9c53a2
runtime.goparkunlock(0x557a4f2dbd40, 0x557a4ed2b78a, 0xe, 0x14, 0x1)
        /usr/lib/golang/src/runtime/proc.go:283 +0x60 fp=0xc420035740 sp=0xc420035700 pc=0x557a4e9c5490
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:175 +0xbc fp=0xc4200357e0 sp=0xc420035740 pc=0x557a4e9aed0c
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200357e8 sp=0xc4200357e0 pc=0x557a4e9f20f1
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:156 +0x64

goroutine 5 [chan receive]:
runtime.gopark(0x557a4f0cba18, 0xc420092058, 0x557a4ed2a954, 0xc, 0xc42002c117, 0x3)
        /usr/lib/golang/src/runtime/proc.go:277 +0x132 fp=0xc420035e70 sp=0xc420035e40 pc=0x557a4e9c53a2
runtime.goparkunlock(0xc420092058, 0x557a4ed2a954, 0xc, 0x17, 0x3)
        /usr/lib/golang/src/runtime/proc.go:283 +0x60 fp=0xc420035eb0 sp=0xc420035e70 pc=0x557a4e9c5490
runtime.chanrecv(0xc420092000, 0xc420035fb0, 0xc420092001, 0x0)
        /usr/lib/golang/src/runtime/chan.go:506 +0x308 fp=0xc420035f60 sp=0xc420035eb0 pc=0x557a4e99dca8
runtime.chanrecv2(0xc420092000, 0xc420035fb0, 0x0)
        /usr/lib/golang/src/runtime/chan.go:393 +0x2b fp=0xc420035f90 sp=0xc420035f60 pc=0x557a4e99d98b
github.com/golang/glog.(*loggingT).flushDaemon(0x557a4f2bc520)
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0xa1 fp=0xc420035fd8 sp=0xc420035f90 pc=0x557a4ea91e31
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420035fe0 sp=0xc420035fd8 pc=0x557a4e9f20f1
created by github.com/golang/glog.init.0
        /builddir/build/BUILD/source-to-image-f9ff77d66250d5b904183fb9af0b1cb98b5aab98/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x20b

goroutine 18 [syscall]:
runtime.notetsleepg(0x557a4f2bc0d8, 0x6fc236223, 0x0)
        /usr/lib/golang/src/runtime/lock_futex.go:227 +0x46 fp=0xc420030760 sp=0xc420030730 pc=0x557a4e9a88f6
runtime.timerproc()
        /usr/lib/golang/src/runtime/time.go:214 +0x2ff fp=0xc4200307e0 sp=0xc420030760 pc=0x557a4e9e2ebf
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200307e8 sp=0xc4200307e0 pc=0x557a4e9f20f1
created by runtime.addtimerLocked
        /usr/lib/golang/src/runtime/time.go:121 +0xef

goroutine 6 [syscall]:
runtime.notetsleepg(0x557a4f2dc0c0, 0xffffffffffffffff, 0x0)
        /usr/lib/golang/src/runtime/lock_futex.go:227 +0x46 fp=0xc420036780 sp=0xc420036750 pc=0x557a4e9a88f6
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:131 +0xa8 fp=0xc4200367a8 sp=0xc420036780 pc=0x557a4e9da8f8
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x24 fp=0xc4200367e0 sp=0xc4200367a8 pc=0x557a4eceae74
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200367e8 sp=0xc4200367e0 pc=0x557a4e9f20f1
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x43
```

This is fedora rawhide and `source-to-image-1.0.9-7.fc27.x86_64`

Edit: so the issue seem to be that s2i expects this to be a file: `~/.docker/config.json`, but in my case, it was a directory -- no idea if docker created it.

**Comment by TomasTomecek** [comment]
Tried upstream git master and it works -- can you please update this in Fedora? @humaton @ingvagabund @hhorak

**Comment by bparees** [comment]
I don't know who maintains the fedora package but it isn't us.  Maybe open a BZ?

**Comment by TomasTomecek** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1510476
