### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by helio-frota** [openshift/source-to-image#847]
**Fedora 27**
**s2i v1.1.8**

How to reproduce:

1. clone https://github.com/bucharest-gold/centos7-s2i-nodejs
2. pip install docker-squash --user
3. make all

```console
BUILDER=bucharestgold/centos7-s2i-nodejs:latest NODE_VERSION=9.4.0 ./test/run.sh
Running s2i build --pull-policy never  file://./test/test-app bucharestgold/centos7-s2i-nodejs:latest bucharestgold/centos7-s2i-nodejs-testapp
ERROR: couldn't parse "file://./test/test-app": url "file://./test/test-app" has non-empty host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4edf87]

goroutine 1 [running]:
panic(0x7ce260, 0xc420012140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/source-to-image/pkg/cmd/cli/cmd.NewCmdBuild.func1(0xc4200a1440, 0xc4201f8d70, 0x3, 0x5)
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/build.go:64 +0x19a7
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200a1440, 0xc4201f8d20, 0x5, 0x5, 0xc4200a1440, 0xc4201f8d20)
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a0fc0, 0xc4201a7e70, 0x48e9d2, 0xc4200a0fc0)
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/source-to-image/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a0fc0, 0x3, 0xc4200a0fc0)
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/s2i/s2i.go:22 +0xcb
STI image 'bucharestgold/centos7-s2i-nodejs:latest' test FAILED (exit code: 2)
make: *** [Makefile:27: test] Error 2
```

**Comment by bparees** [comment]
looks like `file://.` isn't the right syntax, it works fine if you strip the `file://.` and just pass `test/test-app`, or if you use an absolute path `file:///tmp/foo/test-app`

will add logic to prevent the nil pointer error though.

(I think this was a change in golang's url parsing)
